name: build nodejs v22 withssl (win32)

on: 
  workflow_dispatch:
    inputs:
      tag_date:
        description: 'tag date'     
        required: true

env:
  VERSION: 22.14.0

jobs:
  build_windows_32:
    name: Windows-32
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v2
    - name: npm install
      shell: bash
      run: npm install
    - name: Run build script
      continue-on-error: true
      shell: cmd
      run: |
        cd %GITHUB_WORKSPACE%
        call .\windows_trybuild_32.cmd ${{env.VERSION}}
    - name: Run upload script
      shell: cmd
      run: |
        cd %GITHUB_WORKSPACE%
        call .\windows_32.cmd
    - name: Rename
      shell: bash
      run: |
        mv puerts-node/nodejs puerts-node/nodejs_22
    - uses: actions/upload-artifact@v4
      with:
        name: nodejs_bin
        path: puerts-node/**/*
  publish:
    runs-on: ubuntu-latest
    needs: [build_windows_32]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: nodejs_bin
          path: nodejs_bin/
          
      - name: Create Release Asset
        run: |
          cd nodejs_bin/ && tar cvfz ../nodejs_bin_${{env.VERSION}}.tgz nodejs_22 && cd -
          
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: NodeJS_${{env.VERSION}}_ssl_${{ github.event.inputs.tag_date }}
          release_name: NodeJS_${{env.VERSION}}(with ssl)_${{ github.event.inputs.tag_date }}
          draft: false
          prerelease: false
          
      - name: Upload nodejs_bin
        #id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./nodejs_bin_${{env.VERSION}}.tgz
          asset_name: nodejs_bin_${{env.VERSION}}.tgz
          asset_content_type: application/tgz
          